{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://github.com/scipy/scipy/issues/16235",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/scipy/scipy/pull/16397",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "http://www.square16.org/achievement/cve-2023-25399/",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/scipy/scipy/issues/16235#issuecomment-1625361328",
            "tags": [
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-02T11:18:36.341Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 5.5,
              "attackVector": "LOCAL",
              "baseSeverity": "MEDIUM",
              "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "integrityImpact": "NONE",
              "userInteraction": "NONE",
              "attackComplexity": "LOW",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "LOW",
              "confidentialityImpact": "NONE"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2023-25399",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-05-14T19:33:37.465319Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:scipy:scipy:-:*:*:*:*:*:*:*"
            ],
            "vendor": "scipy",
            "product": "scipy",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "lessThan": "1.10.0",
                "versionType": "custom"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "problemTypes": [
          {
            "descriptions": [
              {
                "lang": "en",
                "type": "CWE",
                "cweId": "CWE-401",
                "description": "CWE-401 Missing Release of Memory after Effective Lifetime"
              }
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-05-14T19:35:34.844Z"
        }
      }
    ],
    "cna": {
      "tags": [
        "disputed"
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "status": "affected",
              "version": "n/a"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/scipy/scipy/issues/16235"
        },
        {
          "url": "https://github.com/scipy/scipy/pull/16397"
        },
        {
          "url": "http://www.square16.org/achievement/cve-2023-25399/"
        },
        {
          "url": "https://github.com/scipy/scipy/issues/16235#issuecomment-1625361328"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "A refcounting issue which leads to potential memory leak was discovered in scipy commit 8627df31ab in Py_FindObjects() function. Note: This is disputed as a bug and not a vulnerability. SciPy is not designed to be exposed to untrusted users or data directly."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "text",
              "description": "n/a"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "shortName": "mitre",
        "dateUpdated": "2024-05-13T22:13:32.327721"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2023-25399",
    "state": "PUBLISHED",
    "dateUpdated": "2024-08-02T11:18:36.341Z",
    "dateReserved": "2023-02-06T00:00:00",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "datePublished": "2023-07-05T00:00:00",
    "assignerShortName": "mitre"
  },
  "dataVersion": "5.1"
}